public class HoteltypeToTextalign {
    static final int ALIGN_LEFT = 0;
    static final int ALIGN_CENTER = 1;
    static final int ALIGN_RIGHT = 2;

	private static final int[] array = {
		ALIGN_CENTER, // BOARDTYPE_NONE
		ALIGN_CENTER, // BOARDTYPE_LUXOR
		ALIGN_CENTER, // BOARDTYPE_TOWER
		ALIGN_CENTER, // BOARDTYPE_AMERICAN
		ALIGN_CENTER, // BOARDTYPE_FESTIVAL
		ALIGN_CENTER, // BOARDTYPE_WORLDWIDE
		ALIGN_CENTER, // BOARDTYPE_CONTINENTAL
		ALIGN_CENTER, // BOARDTYPE_IMPERIAL
		ALIGN_CENTER, // BOARDTYPE_NOTHING_YET
		ALIGN_CENTER, // BOARDTYPE_CANT_PLAY_EVER
		ALIGN_CENTER, // BOARDTYPE_I_HAVE_THIS
		ALIGN_CENTER, // BOARDTYPE_WILL_PUT_LONELY_TILE_DOWN
		ALIGN_CENTER, // BOARDTYPE_HAVE_NEIGHBORING_TILE_TOO
		ALIGN_CENTER, // BOARDTYPE_WILL_FORM_NEW_CHAIN
		ALIGN_CENTER, // BOARDTYPE_CANT_PLAY_NOW
		ALIGN_RIGHT,  // CSSCLASS_EMPTY
		ALIGN_LEFT,   // CSSCLASS_PLAYER
		ALIGN_LEFT,   // CSSCLASS_MY_TURN
		ALIGN_LEFT,   // CSSCLASS_NOT_MY_TURN
		ALIGN_RIGHT,  // CSSCLASS_HOLDINGS
		ALIGN_RIGHT,  // CSSCLASS_HOLDINGS_SAFE
		ALIGN_RIGHT,  // CSSCLASS_CASH_TITLE
		ALIGN_RIGHT,  // CSSCLASS_CASH
		ALIGN_LEFT,   // CSSCLASS_HCS_TITLE
		ALIGN_RIGHT,  // CSSCLASS_HCS
	};
	
	public static int lookup(int hoteltype) {
		return array[hoteltype];
	}
}
